### ISSUE TITLE
Task 1.6: Create an abuse case model, using UML Use Case diagram

### ISSUE THREAD

**Issue by joshuag1214** [joshuag1214/ENPM613-Project#6]
Assignment 2, Requirement 6. "Create an abuse case model, using UML Use Case diagram."

**Comment by thefueley** [comment]
Abuse case diagrams created for the following abuse cases: malicious student changes grade, system administrator changes grade, malicious hacker deletes data and/or denies service to Sonic, and Competition changes grade, creates fake student, and creates fake class. There are 5 pages in the diagram, check the bottom of the page. [Abuse Case Diagrams](https://lucid.app/lucidchart/d7bee23c-dc5d-40ea-9522-8844d9091f50/edit?viewport_loc=-167%2C104%2C2247%2C1224%2C.Q4MUjXso07N&invitationId=inv_104928d4-bbd9-4028-a02d-10435a015080)

**Comment by thefueley** [comment]
Ready for review @joshuag1214 @trimpinm @cpettit98 @adiwari

**Comment by joshuag1214** [comment]
I think this would make more sense. It makes it more explicit who is the threat, rather than an admin being a threat type.

**Comment by thefueley** [comment]
Thanks for the input. Will make the change.

**Comment by cpettit98** [comment]
I'm a little confused on what the difference is between the abuse case and security scenario is in #7. Can you provide some context for me?

**Comment by thefueley** [comment]
@trimpinm, there is no difference. The assignment says to create both, but class slides show both in a single document. The abuse use case is the diagram as a whole. The security scenario is the color-coded portions. At least that's how I interpreted the slides. Slides 73 - 75 in Week 4.

**Comment by joshuag1214** [comment]
Ya I'm a bit confused on it as well. I emailed the ta/prof about it. Would a security scenario be like  "Login using another's credentials?"

**Comment by thefueley** [comment]
@joshuag1214, is that all you asked the Prof/TA? I feel that response would be of little help to us. 

Let me lay out how I understand this task and where I am getting this understanding from. The lecture starting at "ABUSE CASE DIAGRAM EXAMPLE" (1:39:38) through "HOW DO WE INTEGRATE ALL THIS ANALYSIS/TECHNIQUES?" (1:45:37). Prof shows an example of an abuse case, which includes the ways an attacker can abuse the system. He shows two different versions, a text-based one and a graphical one. The graphical (UML) style is the one I chose because the grading rubric states: "Abuse case diagram correctly represented/formed, using UML use case diagram." 

At 1:45:04 he shows the abuse case diagram with green and red zones of color. The next slide explains that the scenarios are depicted in the abuse case diagram through colors and dashed lines. To me, that explains how a security scenario is depicted. Since my task was to create abuse cases and security scenarios, I incorporated them into the same diagram, as shown in class. 

I think that if you ask the Prof/TA a question as you show above, you'll get an simple "Yes" reply that doesn't really help us because one can think of a million different examples of how an attacker can abuse a system. However, at 1:38:25, the slide shows that "... one family member for each kind of privilege abuse ...". That tells me that I don't have to list each and every possible abuse I can think of, just account for the different types of attacks rather than each specific one. I think I covered the general types of abuses, but am open to add more if you think I missed a general _**type**_ of attack.

After reading your comment last night, I also emailed the Prof/TA for clarification. I haven't received a response, but here is what I sent, for transparency.

_Hello, Dr. Barber.

I have a question about the abuse case and security scenarios. The slides show an example UML diagram that is color coded. It seems to combine the abuse case and the security scenario into one diagram. I have created a similar one for my project. I'm looking for clarification if this is acceptable as part of our submission this week. This is one of four abuse case / security scenario diagrams. The green indicates normal workflows and the red, successful attacks._ 

![Assignment2-AbuseCase - Competition](https://github.com/user-attachments/assets/bfadaf17-e138-4d93-b9e4-d7c76f31c369)

**Comment by joshuag1214** [comment]
Thanks for the comprehensive reply, I didn't notice the other tabs in your diagram, I'll get on it right now. I didn't get a reply from the Ta/prof yet so I don't they'll get back today.

**Comment by joshuag1214** [comment]
For these UML diagrams, Shouldn't the diagrams start at the initial node and end up somewhere? In this example, after the initial node and login, there's no flow to the other boxes. Also it looks like the diagrams are based around the actors rather than the the abuse case. In this case, the title of this diagram should be "Unauthorized Grade Change." 
![Image](https://github.com/user-attachments/assets/7300e45f-8206-4db1-a330-a2f43b4fea6a)

**Comment by joshuag1214** [comment]
I can help with reworking some of these diagrams if needed.

**Comment by joshuag1214** [comment]
I can make some reworks in a different tab in here: https://lucid.app/lucidchart/d7bee23c-dc5d-40ea-9522-8844d9091f50/edit?invitationId=inv_104928d4-bbd9-4028-a02d-10435a015080&page=.Q4MUjXso07N#?

**Comment by cpettit98** [comment]
Also I think most of these attacks who elevate to "Admin Role" should elevate to professor because as of rn admin isn't listed as being able to enter grades etc. All an admin can do is add and delete an account.

**Comment by thefueley** [comment]
@joshuag1214, there aren't continuous lines and arrows because the steps aren't exactly sequential. I could add connectors for the sake of simplicity, but you'd have to pretend a little bit. For example, a malicious student doesn't need to "send priv esc" only after "navigating to the grades area". He/she could simply send the payload anytime after logging in. The disconnects reflect that. 

To the second comment, I based the diagrams around the actor and the potential abuse, similar to the class examples, see slides 74 and 75. They show the swim lanes, one with the actor, and the other with aspect being abused. I didn't title any of the abuse cases up top, if that's what you're asking about. The name at the top, "Sonic" simply reflects the system but thinking about that now, I should remove that because it also includes the actor, which isn't correct. I'll just remove it entirely.

@cpettit98, Thanks for pointing that out. I created these cases before knowing that restriction. Since I did this before knowing that, my thought was that a sysadmin can do anything. That is usually the case in any system, even if they aren't logged in as the sysadmin, they usually have the dbadmin creds, etc. I will rework this

**Comment by joshuag1214** [comment]
Also, Should the red lines be used to show the path for attack?![Image](https://github.com/user-attachments/assets/1f14afaa-ca66-4d88-bd43-65c2a9e569d7)

For example, "yes" is red, when it is the path to a successful attack
![Image](https://github.com/user-attachments/assets/38818d54-c566-48b6-aaa8-cfd394ff8757)

**Comment by thefueley** [comment]
Diags have been reworked. Ready for next round of reviews.
